- .gitignore
- .travis.yml
- README.md
- api/pom.xml
- api/src/main/java/io/cloudevents/CloudEvent.java
- api/src/main/java/io/cloudevents/CloudEventBuilder.java
- api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java
- api/src/test/java/io/cloudevents/CloudEventBuilderTest.java
- api/src/test/java/io/cloudevents/CloudEventJacksonTest.java
- api/src/test/java/io/cloudevents/util/JacksonMapper.java
- api/src/test/resources/aws.json
- api/src/test/resources/azure.json
- pom.xml
> Proposal for JAva SDK

- api/pom.xml
- api/src/main/java/io/cloudevents/impl/ZonedDateTimeSerializer.java
- api/src/test/java/io/cloudevents/CloudEventBuilderTest.java
Signed-off-by: Fabio José <fabiojose@gmail.com>
In our company we have strong compliance rules and at this moment we are able to use just java 1.8.
Could you accept these changes to make the impl. compatible to java 1.8?
> Make the source compatible to java 1.8

- http/vertx/src/test/java/io/cloudevents/http/vertx/VertxCloudEventsTests.java
Avoiding hard-coded `8080` usage
> Using random port for http server launch

- api/src/main/java/io/cloudevents/v03/CloudEventBuilder.java
- api/src/test/java/io/cloudevents/v03/CloudEventBuilderTest.java
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
Allows providing an external Validator that would allow reusing an existing instance.
Hibernate Validator cannot be started properly in a native executable.
> Allow providing an external validator

- CHANGELOG.md
- README.md
- api/src/main/java/io/cloudevents/CloudEvent.java
- api/src/main/java/io/cloudevents/json/Json.java
- api/src/main/java/io/cloudevents/v02/CloudEventImpl.java
- api/src/main/java/io/cloudevents/v02/http/Unmarshallers.java
- api/src/main/java/io/cloudevents/v03/CloudEventImpl.java
- api/src/main/java/io/cloudevents/v1/CloudEventBuilder.java
- api/src/main/java/io/cloudevents/v1/CloudEventImpl.java
- api/src/main/java/io/cloudevents/v1/http/Marshallers.java
- api/src/test/java/io/cloudevents/v1/CloudEventJacksonTest.java
- api/src/test/java/io/cloudevents/v1/http/HTTPBinaryUnmarshallerTest.java
- api/src/test/java/io/cloudevents/v1/http/HTTPStructuredUnmarshallerTest.java
- kafka/src/main/java/io/cloudevents/v02/kafka/Marshallers.java
The base64 as it is described in the spec should be contained in a data_base64 attribute regardless of the type that's why I created a new param.
I have also remove it from the extensions and now it should be properly marshalled/unmarshalled (see tests).
Let me know if this PR is aligned with what you expect this field to work.
I also added some more clean up. Can't help it :smile:
> Fix base64 marshalling

- README.md
- kafka/README.md
Docs say Transport. Actual link should go to protocol.
> Fix Kafka Transport references

- kafka/README.md
- kafka/src/main/java/io/cloudevents/kafka/CloudEventsKafkaHeaders.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventsKafkaProducer.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventsKafkaHeadersTest.java
Currently, it may be restrictive to use only the `CloudEventsKafkaProducer` class, which seems to support only JSON serialization. 
Developers should be able to use the KafkaProducer class directly, e.g. to use a custom or vender-type serializer (e.g. the Avro Confluent serializer), while still benefiting from this SDK.
This commit add a new CloudEventsKafkaHeaders helper class used to build the Kafka headers
that should be attached either a binary or structured event message.
> Add new CloudEventsKafkaHeaders class for kafka API

- api/src/main/java/io/cloudevents/Extension.java
- core/src/main/java/io/cloudevents/core/extensions/DistributedTracingExtension.java
- core/src/main/java/io/cloudevents/core/extensions/ExtensionsParser.java
- core/src/main/java/io/cloudevents/core/extensions/impl/ExtensionUtils.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
Look at #122
This change:
* Change the signature of `readFromEvent` to accept `CloudEventExtensions`
* Remove `asMap()` and let `Extension` extend `CloudEventExtensions`. Because the number of attributes for a materialized extension is always the same, allocating a map to provide an unstructrured view (needed to write the materialized extension to the cloud event builder) is useless. This solution makes more efficient the implementation of such materialized extensions
> Reworked a bit the Extension interface

- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/extensions/DistributedTracingExtensionTest.java
- core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java
- core/src/test/java/io/cloudevents/core/v1/CloudEventBuilderTest.java
Fix #161
* `CloudEventBuilder` interface now has methods `withId`, `withSource`, ... in a similar fashion to `CloudEventAttributes`.
* `CloudEventBuilder` now fails if the mandatory attributes are not configured
> CloudEventBuilder interface now has withAttribute methods

- core/src/main/java/io/cloudevents/core/message/impl/GenericStructuredMessage.java
- core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java
- core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java
- core/src/main/java/io/cloudevents/core/provider/ExtensionProvider.java
- core/src/test/java/io/cloudevents/core/extensions/DistributedTracingExtensionTest.java
- core/src/test/java/io/cloudevents/core/provider/EventFormatProviderTest.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- http/restful-ws-integration-tests/restful-ws-jersey/src/test/java/io/cloudevents/http/restful/ws/jersey/TestJersey.java
- http/restful-ws-integration-tests/restful-ws-resteasy/src/test/java/io/cloudevents/http/restful/ws/resteasy/TestResteasy.java
- http/restful-ws-integration-tests/restful-ws-spring/src/test/java/io/cloudevents/http/restful/ws/spring/TestSpringBootWithJersey.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/CloudEventsProvider.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventSerializer.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventSerializerTest.java
* Moved EventFormatProvider and ExtensionsParser into provider
* Renamed ExtensionsParser in ExtensionProvider
That should definitely close #122 
> Moved some provider singletons in new provider package

- api/pom.xml
- api/src/main/java/io/cloudevents/types/Time.java
- api/src/test/java/io/cloudevents/types/TimeTest.java
- core/src/test/java/io/cloudevents/core/test/Data.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/resources/v1/json_data_with_fractional_time.json
Fixes parsing of dates like: 2018-04-26T14:48:09.1234Z
Fixes: #175
> fix: sub-second resolution `time` attribute

- api/src/main/java/io/cloudevents/CloudEvent.java
- api/src/main/java/io/cloudevents/CloudEventAttributes.java
- api/src/main/java/io/cloudevents/CloudEventExtensions.java
- api/src/main/java/io/cloudevents/SpecVersion.java
- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- api/src/main/java/io/cloudevents/types/Time.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
- core/src/test/java/io/cloudevents/core/impl/CloudEventImplTest.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
Did another round of Javadoc to `cloudevents-api` module.
Also changed and clarified the `getAttributeNames()` semantic (the previous semantic was useless, because it was equal to `getSpecVersion().getAllAttributes()`)
> Javadoc-ed cloudevents-api

- examples/pom.xml
- examples/vertx/README.md
- examples/vertx/pom.xml
- examples/vertx/src/main/java/io/cloudevents/examples/vertx/SampleHTTPClient.java
- examples/vertx/src/main/java/io/cloudevents/examples/vertx/SampleHTTPServer.java
Part of #125 
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
> Add Vertx example

- benchmarks/pom.xml
- benchmarks/src/main/java/io/cloudevents/bench/jackson/JsonFormatDeserializationBenchmark.java
- benchmarks/src/main/java/io/cloudevents/bench/jackson/JsonFormatSerializationBenchmark.java
- benchmarks/src/main/java/io/cloudevents/bench/kafka/CloudEventToKafkaProducerMessageBenchmark.java
- benchmarks/src/main/java/io/cloudevents/bench/kafka/KafkaConsumerMessageToCloudEventBenchmark.java
- pom.xml
This PR introduces a new module to host microbenchmarks of the various core features and integrations. I opted for a single module for simplicity and because it may be useful in future to add benchs to cross test performance between one integration and another (eg from vertx to kafka).
The benchmarks added in this PR are about:
* JsonFormat serialization and deserialization
* CloudEvent read/write from/to Kafka
> Added json format & kafka benchmarks

- README.md
Fixes README link.
Uses absolute URL for different git branch.
> docs: fix README link. Fixes #210

- api/src/main/java/io/cloudevents/CloudEventAttributes.java
- api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
- api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
- api/src/main/java/io/cloudevents/types/Time.java
- api/src/test/java/io/cloudevents/types/TimeTest.java
- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
- core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
- core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- core/src/test/java/io/cloudevents/core/test/Data.java
- formats/json-jackson/src/test/resources/v1/json_data_with_fractional_time.json
- http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpClientRequestMessageWriterTest.java
- http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpServerResponseMessageWriterTest.java
- http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
- kafka/src/test/java/io/cloudevents/kafka/KafkaMessageFactoryTest.java
- kafka/src/test/java/io/cloudevents/kafka/KafkaProducerMessageWriterTest.java
Fix #214
There is also a small change that prevented travis to correctly build the module (while building, the cache was using an old version of cloudevents-api)
Mind giving a look @pwall-tyro ?
> Switch `ZonedDateTime` to `OffsetDateTime`

- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
> Added a method to remove the extensions

- core/README.md
- docs/index.md
- scripts/release.md
- scripts/trigger_release.sh
* Created scripts to perform master commits to trigger automation, like explained for #190
* Added documentation on how to perform a release
* Some nits to the docs in order to work well with the release script
Fix #190
> Release automation

- api/README.md
- api/pom.xml
- benchmarks/pom.xml
- core/README.md
- core/pom.xml
- examples/kafka/pom.xml
- examples/pom.xml
- examples/vertx/pom.xml
- formats/json-jackson/pom.xml
- http/restful-ws-integration-tests/pom.xml
- http/restful-ws-integration-tests/restful-ws-common/pom.xml
- http/restful-ws-integration-tests/restful-ws-jersey/pom.xml
- http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml
- http/restful-ws-integration-tests/restful-ws-spring/pom.xml
- http/restful-ws/pom.xml
- http/vertx/pom.xml
- kafka/README.md
- kafka/pom.xml
- pom.xml
> Release 2.0.0-milestone2

- examples/basic-http/pom.xml
- examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/BasicHttpServer.java
- examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/HttpURLConnectionClient.java
- examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/IOUtils.java
- examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/JettyServer.java
- examples/pom.xml
- http/basic/README.md
- http/basic/pom.xml
- http/basic/src/main/java/io/cloudevents/http/HttpMessageFactory.java
- http/basic/src/main/java/io/cloudevents/http/impl/CloudEventsHeaders.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java
- http/basic/src/test/java/io/cloudevents/http/HttpMessageReaderWriterTest.java
- pom.xml
> Generic HTTP bindings

- .travis.yml
Signed-off-by: ruromero <rromerom@redhat.com>
The Quarkus tests will require the other cloudevents libraries to be in the local maven repository, that's why the goal has been changed from `verify` to `install`
> Fix Graalvm travis build

- examples/restful-ws-quarkus/src/main/resources/application.properties
- http/restful-ws/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
Signed-off-by: ruromero <rromerom@redhat.com>
With these changes, the CloudEventsProvider will be picked up automatically by any library depending on the java-sdk. Look at the changes removed from the restful-ws-quarkus example.
> Add CloudEventsProvider to services

- .github/workflows/bump.yaml
Also fixed the substitution command in the non snapshot bumps
> Now bump doesn't add pom backups

- api/src/main/java/io/cloudevents/types/Time.java
- api/src/test/java/io/cloudevents/types/TimeTest.java
- formats/json-jackson/src/test/resources/v1/json_data_with_fractional_time.json
According to the [documentation](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#toString--), `OffsetDateTime`'s `toString` method uses this format `uuuu-MM-dd'T'HH:mmXXXXX` when seconds is zero. This is incompatible with RFC3339 and cannot be parsed by other cloud events SDKs. 
Here is an demo of the incompatibility:
https://play.golang.org/p/9db3zuJTM_k
> Serialize time to RFC3339 compliant string

- api/src/main/java/io/cloudevents/CloudEvent.java
- api/src/main/java/io/cloudevents/CloudEventData.java
- api/src/main/java/io/cloudevents/rw/CloudEventWriter.java
- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/data/BytesCloudEventData.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/HttpURLConnectionClient.java
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/resources/UserResource.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/BinaryRestfulWSMessageReaderImpl.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSClientMessageWriter.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageWriter.java
- http/vertx/src/main/java/io/cloudevents/http/vertx/impl/BinaryVertxMessageReaderImpl.java
- http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxHttpServerResponseMessageWriterImpl.java
- http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxWebClientRequestMessageWriterImpl.java
- kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageWriterImpl.java
- kafka/src/main/java/io/cloudevents/kafka/impl/KafkaBinaryMessageReaderImpl.java
I thought a little bit about the problem with the data representation. To do a little recap, we have open these issues/PRs with various discussions about this topic:
* https://github.com/cloudevents/sdk-java/issues/196
* https://github.com/cloudevents/sdk-java/issues/238
* https://github.com/cloudevents/sdk-java/pull/198
* https://github.com/cloudevents/sdk-java/pull/208
* https://github.com/cloudevents/sdk-java/pull/211
I tried to put together all the different discussions we had, the different feedbacks and prepare a proposal to solve the issue, hopefully once and for all :smile: 
These are the problems we're trying to tackle:
* Users wants to read/write pojos in their CloudEvents, making the experience as nice as possible
* We want to enforce serialization/deserialization to bytes, but …
> Introduce CloudEventData

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonCloudEventData.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
Followup of #250
This implements an optimization in the jackson CloudEvent ser/de that allows users to directly provide a `JsonNode` as `CloudEvent` data, avoiding the double serialization/deserialization problem.
This is inspired by the discussions here: https://github.com/cloudevents/sdk-java/issues/196
> Introduce JsonCloudEventData

- api/src/main/java/io/cloudevents/CloudEventData.java
- api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/format/EventFormat.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- core/src/test/java/io/cloudevents/core/mock/MyCloudEventData.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonCloudEventData.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonCloudEventDataTest.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventDeserializer.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventDeserializerTest.java
This PR introduces an interface to perform the mapping of `CloudEventData` and integrates it in the read process.
Now the user, when reading an event, can provide a mapper that converts the parsed `CloudEventData`, in whatever shape it is, to the desired data payload. **The mapper is consistently invoked both when messages are in structured mode or binary mode**: in this way, users define their own `CloudEventData`, along with `CloudEventDataMapper`, and they can consistently access to the event payloads, no matter from which "medium" the event came from.
When message is transcoded from one message to another, without going through `Event` (look at `MessageReader#visit` method), the mapper is not invoked.
Because we reuse `CloudEventData`, the user can eventually develop optimizations in …
> CloudEventDataMapper

- api/src/main/java/io/cloudevents/CloudEvent.java
- api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventUtils.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
- core/src/test/java/io/cloudevents/core/impl/CloudEventUtilsTest.java
This PR adds a new method to `CloudEventUtils`, called `mapData(event, mapper)` (implemented by default), to improve the user experience with mappers. Now we finally have a good user experience for data: users can now safely map event payloads to business objects without casting and without any knowledge of the sdk itself:
```java
MyPojo myPojo = mapData(event, PojoCloudEventDataMapper.from(objectMapper, new TypeReference<MyPojo>() {})) // PojoCloudEventDataMapper<MyPojo>
.getValue();
```
(note: this example is using json mapper which is proposed in another pr independent from this one)
To make this possible, I also generified the return value of CloudEventDataMapper
> CloudEventUtils.mapData(event, mapper)

- api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventData.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/MyPojo.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
Implemented a `CloudEventDataMapper` and a `CloudEventData` that uses jackson json mapper to map `CloudEventData` to pojos
> Json mapper

- kafka/README.md
- kafka/src/main/java/io/cloudevents/kafka/CloudEventDeserializer.java
- kafka/src/main/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptor.java
- kafka/src/test/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptorTest.java
This implements a `ProducerInterceptor` that sets up the proper partition key from the `CloudEvent` extension
Fixes #94
> PartitionKey Kafka Interceptor

- api/src/main/java/io/cloudevents/rw/CloudEventContextReader.java
- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventUtils.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- http/basic/src/main/java/io/cloudevents/http/HttpMessageFactory.java
- http/basic/src/test/java/io/cloudevents/http/HttpMessageReaderWriterTest.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageSerializer.java
* Extracted `readAttributes` and `readExtensions` from `CloudEventReader` and moved to `CloudEventContextReader`: This relaxes the assumption that any `CloudEventReader` has attributes and extensions buffered and it avoids to create empty implementations of `readAttributes`/`readExtensions` for protocol bindings (in protocol bindings context, only `read` is ever used).
* Added `CloudEventUtils#toContextReader` to create a context reader starting from a `CloudEvent` (in fact, works the same as `CloudEventUtils#toVisitable`
* Improved documentation of *Reader interfaces
* Renamed `MessageReader#visit` to the proper name `MessageReader#read`
> Improvements to CloudEventReader

- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
Signed-off-by: Matej Vasek <mvasek@redhat.com>
> feat: new overload for mapper factory

- core/src/main/java/io/cloudevents/core/CloudEventUtils.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/MessageWriter.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/CloudEventUtilsTest.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventMessageSerializerTest.java
Because `CloudEventUtils` now contains utilities useful to deal with conversions, often useful for end users of the sdk (look at `mapData`), I think it's reasonable to make it more visible and push it in the main package `cloudevents-core`.
Also:
* Renamed `CloudEventUtils#toVisitable` to `CloudEventUtils#toReader`
* Added `CloudEventUtils#toEvent` methods to convert a `CloudEventReader` to a `CloudEvent`
> Moved CloudEventUtils to io.cloudevents.core

- api/src/main/java/io/cloudevents/CloudEventData.java
- api/src/main/java/io/cloudevents/CloudEventExtensions.java
- api/src/main/java/io/cloudevents/Extension.java
- api/src/main/java/io/cloudevents/SpecVersion.java
- api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
- api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
- api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- api/src/main/java/io/cloudevents/rw/CloudEventWriter.java
- api/src/main/java/io/cloudevents/rw/CloudEventWriterFactory.java
- api/src/main/java/io/cloudevents/types/Time.java
- api/src/test/java/io/cloudevents/SpecVersionTest.java
- api/src/test/java/io/cloudevents/types/TimeTest.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventData.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
Also:
* Cleanup the `CloudEventRWException`
* Added a bunch of tests in api module
* Added in `Time` overrides of `parseTime` and `writeTime` to generate the proper `CloudEventRWException`. Also using this methods when appropriate
> Javadoc'ed + Cleanup of the api module

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #271
> CloudEventBuilder should fail when providing an invalid extension name

- pom.xml
It's nice to have sources in the IDE.
> Add sources plugin to Maven build

- api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- core/src/main/java/io/cloudevents/core/CloudEventUtils.java
- core/src/main/java/io/cloudevents/core/format/EventFormat.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/message/MessageReader.java
- core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
- core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventDeserializerTest.java
Fix #285
* Now, across all the different interfaces we have, `CloudEventDataMapper` cannot be null
* Cleanup of all mapper != null and replaced with CloudEventDataMapper.identity()
* Fixed all the missing wildcards
> Introduce CloudEventDataMapper.identity()

- .gitignore
- api/src/main/java/io/cloudevents/CloudEventContext.java
- core/src/main/java/io/cloudevents/core/CloudEventUtils.java
- core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventContextReaderAdapter.java
- core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
- core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java
- core/src/test/java/io/cloudevents/core/v1/CloudEventBuilderTest.java
As discussed in #293 this change introduces a new interface
that extends CloudEventAttributes and CloudEventExtensions.
A builder would be nice, but it's a much bigger change.
Also the BaseBuilder method signatures use CloudEvent when
they could use CloudEventContext, but there's no way to fix
that without major disruption either.
> Introduce CloudEventContext

- amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpMessageWriter.java
- amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageFactoryTest.java
- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- http/basic/src/main/java/io/cloudevents/http/impl/CloudEventsHeaders.java
- kafka/src/main/java/io/cloudevents/kafka/impl/KafkaHeaders.java
- kafka/src/main/java/io/cloudevents/kafka/impl/KafkaProducerMessageWriterImpl.java
There are important constants in the cloud event API that are widely used throughout the SDK. Such constants should reside in one place and be properly documented (possibly adding references to the respective section of the spec).
This patch attempts to put all constants for property names and prefixes for protocol bindings in one place.
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
> [Refactoring] Aggregate widely used constants.

- amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpBinaryMessageReader.java
- core/src/main/java/io/cloudevents/core/data/BytesCloudEventData.java
- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/BinaryRestfulWSMessageReaderImpl.java
- http/vertx/src/main/java/io/cloudevents/http/vertx/impl/BinaryVertxMessageReaderImpl.java
- kafka/src/main/java/io/cloudevents/kafka/impl/KafkaBinaryMessageReaderImpl.java
This is done to be consistent with #289. Also deprecating the constructor to force users to use the static method
> Add method `BytesCloudEventData#wrap`

- http/vertx/pom.xml
A new Vertx release is out, bumping version.
> Bump Vertx from 4.0.0.Beta1 to 4.0.0.CR2

- README.md
- examples/README.md
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserEventsGenerator.java
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/resources/UserResource.java
* Also improved the quarkus example to use the new CloudEventData api
* Also added to the root readme amqp and http basic
> Examples readme

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
The change in #296 could have simplified the constructor 
further. This change does that.
> Simplify BaseCloudEventBuilder constructor

- amqp/README.md
Adds a `README.md` file in the amqp module directory. This follows the README format found in the other bindings
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
> add README.md for AMQP binding

- http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
- http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
When a request contains an invalid event, the body handler doesn't
handle the exception, which leads to an unhandled exception.
```
SEVERE: Unhandled exception
io.cloudevents.rw.CloudEventRWException: Invalid specversion: 9000.1
at io.cloudevents.rw.CloudEventRWException.newInvalidSpecVersion(CloudEventRWException.java:87)
at io.cloudevents.SpecVersion.parse(SpecVersion.java:76)
at io.cloudevents.core.message.impl.MessageUtils.parseStructuredOrBinaryMessage(MessageUtils.java:57)
at io.cloudevents.http.vertx.VertxMessageFactory.createReader(VertxMessageFactory.java:42)
at io.cloudevents.http.vertx.VertxMessageFactory.lambda$createReader$4(VertxMessageFactory.java:63)
at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
at …
```
> [Vertx] Fail promise on create reader exception

- pom.xml
- spring/README.md
- spring/pom.xml
- spring/src/main/java/io/cloudevents/spring/http/CloudEventHttpUtils.java
- spring/src/main/java/io/cloudevents/spring/http/CloudEventsHeaders.java
- spring/src/main/java/io/cloudevents/spring/http/package-info.java
- spring/src/main/java/io/cloudevents/spring/mvc/CloudEventHttpMessageConverter.java
- spring/src/main/java/io/cloudevents/spring/mvc/package-info.java
- spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
- spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageWriter.java
- spring/src/main/java/io/cloudevents/spring/webflux/package-info.java
- spring/src/test/java/io/cloudevents/spring/mvc/MvcRestControllerTests.java
- spring/src/test/java/io/cloudevents/spring/webflux/WebFluxRestControllerTests.java
Supports MVC and WebFlux (blocking and non-blocking) HTTP.
User can work with `CloudEvent` as a `POJO` type and inject it
into `@ReqestMapping` methods.
Further work is needed to provide support for messaging
and functions.
This is a partial replacement for #302.
> HTTP converters for CloudEvent in Spring

- .gitignore
- amqp/README.md
The path to the example client and server files specified in the amqp-proton Readme.md file is wrong and leads to a `404 Not Found` error when the link is visited.
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
> Fix 404 Not Found in AMQP module Readme

- amqp/src/main/java/io/cloudevents/amqp/ProtonAmqpMessageFactory.java
- amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageFactoryTest.java
- pom.xml
* Aligned the amqp javadocs to the others
* Fixed external links
> AMQP javadocs

- kafka/src/main/java/io/cloudevents/kafka/CloudEventDeserializer.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageDeserializer.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageSerializer.java
- kafka/src/main/java/io/cloudevents/kafka/CloudEventSerializer.java
- kafka/src/main/java/io/cloudevents/kafka/KafkaMessageFactory.java
- kafka/src/main/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptor.java
- pom.xml
* Kafka module javadocs
* Added link to kafka
> Kafka javadocs

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonCloudEventData.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
- pom.xml
* Added Jackson javadocs (fixing external linking too)
* Deprecated the constructor of `JsonCloudEventData` and added the `wrap` method (aligning with core data impls)
* Now `CloudEventSerializer` and `CloudEventDeserializer` classes are package privates (this shouldn't be a breaking change, because these classes had non public constructors anyway). Users can continue to use the `JsonFormat#getCloudEventJacksonModule` methods to register these constructors in their object mappers
> Jackson javadocs

- docs/spring.md
- examples/pom.xml
- examples/spring-rsocket/README.md
- examples/spring-rsocket/pom.xml
- examples/spring-rsocket/src/main/java/io/cloudevents/examples/spring/DemoApplication.java
- examples/spring-rsocket/src/main/java/io/cloudevents/examples/spring/Foo.java
- examples/spring-rsocket/src/main/resources/application.properties
- examples/spring-rsocket/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java
- spring/pom.xml
- spring/src/main/java/io/cloudevents/spring/codec/CloudEventDecoder.java
- spring/src/main/java/io/cloudevents/spring/codec/CloudEventEncoder.java
- spring/src/test/java/io/cloudevents/spring/codec/CloudEventDecoderTests.java
- spring/src/test/java/io/cloudevents/spring/codec/CloudEventEncoderTests.java
Also generically can support structured events with any Spring
API that works with Encoder and Decoder. There's a sample for
the RSocket case with a simple request-response echo server.
> Add support for RSockets with Spring

- api/src/main/java/io/cloudevents/rw/CloudEventContextWriter.java
- api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/test/Data.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/resources/v03/fail_numeric_decimal.json
- formats/json-jackson/src/test/resources/v03/fail_numeric_long.json
- formats/json-jackson/src/test/resources/v1/fail_numeric_decimal.json
- formats/json-jackson/src/test/resources/v1/fail_numeric_long.json
- formats/json-jackson/src/test/resources/v1/numeric_ext.json
- Added tests case to verify expected handling of numeric context attributes.
- Updated serializer.
Ideally we'd change the `CloudEventContextWriter` and replace the set(name, Number) method with a set(name, Integer) method to ensure that all future implementations.
I'm happy to make that change now based on feedback.
Closes #357 
Signed-off-by: Day, Jeremy(jday) <jday@paypal.com>
> Specification Compliant handling of numeric context attributes

- core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java
- core/src/test/java/io/cloudevents/core/message/impl/MessageUtilsTest.java
- Modfy logic that selects between structured and binary modes during reception.
- Introduced new test scenarios to veify behavior.
Closes #361 
Signed-off-by: Day, Jeremy(jday) <jday@paypal.com>
> Throw exceptions when attempting to handle unsupported CloudEvent formats

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
As per spec [1], attribute names SHOULD NOT and not MUST NOT
exceed 20 characters in length.
[1] https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention
> CloudEvents attribute names SHOULD NOT exceed 20 chars

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
As per title.
There is no need to allocate another array.
> Avoid allocating an array on extension validation

- sql/src/main/java/io/cloudevents/sql/impl/expressions/LikeExpression.java
- sql/src/test/resources/tck/like_expression.yaml
Now like regex impl properly escapes pattern chunks
> Fix like expression

- README.md
The guide site of http4k has been updated.
> Update the link to http4k Cloud Events module.

- sql/src/main/java/io/cloudevents/sql/EvaluationRuntime.java
- sql/src/main/java/io/cloudevents/sql/impl/EvaluationRuntimeImpl.java
- sql/src/main/java/io/cloudevents/sql/impl/FailFastExceptionThrower.java
- sql/src/test/java/io/cloudevents/sql/impl/EvaluationRuntimeImplTest.java
Provide a simpler interface to perform casting outside an expression. This is useful when the output result of the expression needs to be coerced to a specific type, eg when using for filtering, you always need to coerce the result back to boolean.
> [CESQL] Simpler interface to perform casting

- sql/src/main/java/io/cloudevents/sql/EvaluationException.java
- sql/src/main/java/io/cloudevents/sql/ParseException.java
- sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactory.java
- sql/src/main/java/io/cloudevents/sql/impl/expressions/AccessAttributeExpression.java
- sql/src/main/java/io/cloudevents/sql/impl/expressions/DivisionExpression.java
- sql/src/main/java/io/cloudevents/sql/impl/expressions/FunctionInvocationExpression.java
- sql/src/main/java/io/cloudevents/sql/impl/expressions/ModuleExpression.java
- sql/src/main/java/io/cloudevents/sql/impl/functions/LeftFunction.java
- sql/src/main/java/io/cloudevents/sql/impl/functions/RightFunction.java
- sql/src/main/java/io/cloudevents/sql/impl/functions/SubstringFunction.java
- sql/src/main/java/io/cloudevents/sql/impl/functions/SubstringWithLengthFunction.java
- sql/src/main/java/io/cloudevents/sql/impl/parser/ExpressionTranslatorVisitor.java
- sql/src/main/java/io/cloudevents/sql/impl/parser/ParserImpl.java
- sql/src/main/java/io/cloudevents/sql/impl/runtime/TypeCastingProvider.java
This gives us more freedom to modify and break these methods, and makes the Exceptions public APIs more streamlined.
> Moved exception factory methods internally

- core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventDeserializerTest.java
Signed-off-by: Dmitrii Bocharov <dmitrii.bocharov@embedit.cz>
> fix NPE in CloudEventDeserializer when deserializing with optional header with null value

- spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
Hi,
the input stream has not been closed correctly.
Fixes #420
> Close input stream on CloudEventHttpMessageReader fix #420

- api/src/main/java/io/cloudevents/rw/CloudEventReader.java
- pom.xml
- https://vertx.io/docs/apidocs/ returns 404, so removing it
- Fix Java Doc error for missing `@param`
> Fix the Java Doc build

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormatOptions.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/resources/v03/json_data_with_ext_invalid.json
- formats/json-jackson/src/test/resources/v03/json_data_with_ext_upper_case.json
- formats/json-jackson/src/test/resources/v1/json_data_with_ext_invalid.json
- formats/json-jackson/src/test/resources/v1/json_data_with_ext_upper_case.json
CloudEventDeserializer by cloudevents-json-jackson throws an exception when an invalid extension key is included.
Since the extension attribute is not a madatory value, why don't CloudEventDeserializer ignore invalid attributes and run Deserialize?
I modified to ignore the invalid extensionName in CloudEventDeserializer. 
Fixes #428
> Ignore not valid extension name in jackson CloudEventDeserializer

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/resources/v03/min_subject_null.json
- formats/json-jackson/src/test/resources/v1/min_subject_null.json
In `getOptionalStringNode` we should handle `JsonNode`s that are
instances of `NullNode`.
Fixes #430
> Handle NullNode for optional attributes in Jackson CloudEventDeserializer

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/resources/v03/min_subject_null.json
- formats/json-jackson/src/test/resources/v1/min_subject_null.json
Cherry-pick of https://github.com/cloudevents/sdk-java/pull/432
> [2.2] Handle NullNode for optional attributes in Jackson CloudEventDeserializer

- spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
Cherry-pick of https://github.com/cloudevents/sdk-java/pull/421
> [2.2] Close input stream on CloudEventHttpMessageReader (#421)

- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoSerializer.java
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoSupport.java
- formats/protobuf/src/test/java/io/cloudevents/protobuf/ProtoSupportTest.java
Ensures correct protobuf field usage for text based content.
Moved content-type introspection in a seprate support class.
Added unit tests to ensure introspection is correct.
Fixes #443
> Enhances detection of textual content-types

- CONTRIBUTING.md
- MAINTAINERS.md
These 2 new files are based on the existing `pr_guidelines.md`
and `maintainers_guide.md` + some copied content from
https://github.com/cloudevents/sdk-javascript.
I don't know how to test this, so I'll re-check the reports linked
in https://github.com/cloudevents/sdk-java/issues/453 after merge.
> Add `CONTRIBUTING.md` and `MAINTAINERS.md` files for CLO monitor

- core/src/main/java/io/cloudevents/core/impl/StringUtils.java
- core/src/test/java/io/cloudevents/core/impl/StringUtilsTest.java
- http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
- http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/BinaryRestfulWSMessageReaderImpl.java
- http/vertx/src/main/java/io/cloudevents/http/vertx/impl/BinaryVertxMessageReaderImpl.java
- kafka/src/main/java/io/cloudevents/kafka/impl/KafkaBinaryMessageReaderImpl.java
- spring/src/main/java/io/cloudevents/spring/messaging/MessageBinaryMessageReader.java
Instead of using:
```java
key.substring(0, CE_PREFIX.length()).toLowerCase().startsWith(CE_PREFIX);
```
that allocates 2 new strings, we can just use:
```java
key.regionMatches(true /* ignoreCase */, 0, CE_PREFIX, 0, CE_PREFIX.length());
```
> Optimize `isCloudEventsHeader` check

- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserClient.java
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/resources/UserResource.java
* Server accepts both: binary and structured encoded events.
* Emitter contains comment describing how to switch between binary and
structured encoding for emitted events.
Closes #465
> chore: update Quarkus example

- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonCloudEventDataTest.java
Fixes https://github.com/cloudevents/sdk-java/issues/470
Now checks if dataContentType matches the next regex.
`^(application|text)\/([a-zA-Z]+\+)?json$")`
This regex support 
`application/foobar+json`
or standard
```
application/json
text/json
```
> support dynamic data content type

- docs/core.md
Was using `ExtensionParser` instead `ExtensionProvider`
> Fix example in "Materialize an Extension"

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
I noticed the url in the Java doc was not correct. As it turns out using a regex is about ten times slower for this case, so I removed that part of the commit.
> Set correct url to naming conventions.

- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
Fixes https://github.com/cloudevents/sdk-java/issues/481
Signed-off-by: Frederic Delechamp <fdelechamp@guidewire.com>
> fix: strip parameters from data content types to assess if it's JSON format

- core/src/test/java/io/cloudevents/core/data/PojoCloudEventDataTest.java
- core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
- core/src/test/java/io/cloudevents/core/mock/MyCloudEventData.java
- core/src/test/java/io/cloudevents/core/test/Data.java
- docs/core.md
- examples/amqp-proton/src/main/java/io/cloudevents/examples/amqp/vertx/AmqpClient.java
- examples/amqp-proton/src/main/java/io/cloudevents/examples/amqp/vertx/AmqpServer.java
- examples/kafka/src/main/java/io/cloudevents/examples/kafka/SampleProducer.java
- examples/restful-ws-microprofile-liberty/src/main/java/io/cloudevents/examples/microprofile/CloudEventsJaxrsService.java
- examples/spring-reactive/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java
- examples/spring-reactive/src/test/java/io/cloudevents/examples/spring/WebClientTests.java
- examples/vertx/src/main/java/io/cloudevents/examples/vertx/SampleHTTPClient.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonCloudEventData.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
- kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageWriterImpl.java
- kafka/src/test/java/io/cloudevents/kafka/CloudEventDeserializerTest.java
- kafka/src/test/java/io/cloudevents/kafka/KafkaMessageFactoryTest.java
- kafka/src/test/java/io/cloudevents/kafka/KafkaProducerMessageWriterTest.java
- kafka/src/test/java/io/cloudevents/kafka/KafkaUtils.java
- spring/src/main/java/io/cloudevents/spring/messaging/CloudEventMessageConverter.java
- spring/src/test/java/io/cloudevents/spring/codec/CloudEventDecoderTests.java
- spring/src/test/java/io/cloudevents/spring/codec/CloudEventEncoderTests.java
- spring/src/test/java/io/cloudevents/spring/messaging/CloudEventMessageConverterTests.java
Closes #488
Signed-off-by: Doug Davis <dug@microsoft.com>
> Use UTF-8 when using getBytes

- examples/restful-ws-quarkus/README.md
- examples/restful-ws-quarkus/examples/user_structured.json
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserClient.java
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserEventsGenerator.java
- examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/resources/UserResource.java
I have updated the Quarkus example to emit both Structured and Binary events
Fixes https://github.com/cloudevents/sdk-java/issues/465
> [#465] Upgrade Quarkus examples with binary and structured events

- docs/protobuf.md
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoCloudEventData.java
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoDataWrapper.java
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoDeserializer.java
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoSerializer.java
- formats/protobuf/src/test/java/io/cloudevents/protobuf/ProtoDataWrapperTest.java
- formats/protobuf/src/test/java/io/cloudevents/protobuf/ProtoMessageDataTest.java
Modified ProtoCloudEventData to  _always_ return a Protobuf _Any_ object - this ensures it is coherent with the Protobuff CloudEvent format specification.
It remains possible to wrap any Protobuf 'Message' object directly (which includes an 'Any')  as a convienience to reduce application code.
Closes #532
> Make ProtoCloudEventData consistent with spec.

- core/src/main/java/io/cloudevents/core/format/ContentType.java
- core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java
- core/src/test/java/io/cloudevents/core/provider/EventFormatProviderTest.java
- docs/json-jackson.md
- docs/protobuf.md
- docs/xml.md
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
- formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtobufFormat.java
- formats/xml/src/main/java/io/cloudevents/xml/XMLFormat.java
Closes #537
```java
import io.cloudevents.CloudEvent;
import io.cloudevents.core.format.EventFormatProvider;
import io.cloudevents.core.builder.CloudEventBuilder;
import io.cloudevents.core.format.ContentType; // New constant to facilitate loose coupling in client applications
CloudEvent event = ...;
byte[] serialized = EventFormatProvider
.getInstance()
.resolveFormat(ContentType.PROTO) // EventFormatProvider.resolveFormat(...) overloaded 
.serialize(event);                // for string and enum input options
```
> Refactor to Facilitate Decoupling from Concrete Implementations of EventFormat

- sql/src/test/java/io/cloudevents/sql/TCKTestSuite.java
- sql/src/test/resources/tck/README.md
- sql/src/test/resources/tck/like_expression.yaml
- sql/src/test/resources/tck/subscriptions_api_recreations.yaml
I recently realized that the tck tests for CESQL are not up to date with the new ones added in the spec repo. This PR just copies those changes over into sdk-go, and registers the new test file.
cc @duglin @pierDipi
> Sync CESQL tck tests

- formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
- formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormatOptions.java
- formats/json-jackson/src/test/java/io/cloudevents/jackson/CloudEventDeserializerTest.java
For JSON structured CE we may assume JSON `datacontenttype` as long as `data` is present int the CE.
> feat: JSON format to assume JSON content-type where possible

- examples/amqp-proton/pom.xml
- examples/basic-http/pom.xml
- examples/kafka/pom.xml
- examples/restful-ws-microprofile-liberty/pom.xml
- examples/restful-ws-quarkus/pom.xml
- examples/restful-ws-spring-boot/pom.xml
- examples/rocketmq/pom.xml
- examples/spring-function/pom.xml
- examples/spring-reactive/pom.xml
- examples/spring-rsocket/pom.xml
- examples/vertx/pom.xml
- http/restful-ws-integration-tests/restful-ws-common/pom.xml
- http/restful-ws-integration-tests/restful-ws-jersey/pom.xml
- http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml
- http/restful-ws-integration-tests/restful-ws-spring/pom.xml
- http/restful-ws-jakarta-integration-tests/restful-ws-jakarta-common/pom.xml
- http/restful-ws-jakarta-integration-tests/restful-ws-jersey/pom.xml
- http/restful-ws-jakarta-integration-tests/restful-ws-liberty/pom.xml
- http/restful-ws-jakarta-integration-tests/restful-ws-resteasy/pom.xml
Inspired by [Automatic-Module-Name: Calling All Java Library Maintainers](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers), I added the module names for the non-specified modules on their respective `pom.xml` file
Solves #638
> fix: invalid automatic module name

- .github/workflows/bump.yaml
This will allow changing the version in the documentation website when a new release is published.
> Allow bumping versions in `/docs` only

- core/src/main/java/io/cloudevents/core/provider/CloudEventValidatorProvider.java
> Make CloudEventValidatorProvider thread safe

- bom/pom.xml
Importing CE's BOM in Java project and then trying to use `cloudevents-sql` specifically as dependency results in `not found` error. Due to incorrect `artifactId` in BOM file itself. 
Also checking the managed deps in Maven Central, `io.cloudevents.sql` doesn't follow the convention. And visually it doesn't seem to be recognized and linked to artifact itself. 
https://mvnrepository.com/artifact/io.cloudevents/cloudevents-bom/4.0.1
This is artifact the BOM should be point at: https://mvnrepository.com/artifact/io.cloudevents/cloudevents-sql/4.0.1
> Fix cloudevents-sql artifactId in bom

- core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
- core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
- core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java
- core/src/test/java/io/cloudevents/core/v1/CloudEventBuilderTest.java
- formats/avro-compact/src/test/java/io/cloudevents/avro/compact/AvroCompactFormatTest.java
Specification clearly states that 'subject' is optional but if present, MUST be non-empty (spec at https://github.com/cloudevents/spec/blob/v1.0/spec.md#subject)
Fixes #676
> fix: disallow empty 'subject' header

- formats/protobuf/pom.xml
Upgrade protobuf to 4.3.1. 
This is the latest version of protobuf, no changes for the wire format but the library is not compatible with 3.x so we might need a major release for it
https://github.com/cloudevents/sdk-java/issues/694
> upgrade to protobuf sdk 4.31.1
