pom.xml
=> Adding scm coordinates

README.md
=> Adding travis badge

api/pom.xml, api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java, api/src/main/java/io/cloudevents/impl/ZonedDateTimeDeserializer.java
support for Jackson's `StdDeserializer`, adding hooks for `ZonedDateTime` clazz
=> Adding deserializer for ZonedDateTime

api/src/main/java/io/cloudevents/impl/ZonedDateTimeSerializer.java
Signed-off-by: Fabio José <fabiojose@gmail.com>
=> Inclusion of a serializer for ZonedDateTime

.travis.yml, api/src/test/java/io/cloudevents/CloudEventBuilderTest.java
FYI @fabiojose, adding travis CI builds for the "new" env.
=> adding jdk 8 CI builds

api/src/main/java/io/cloudevents/CloudEvent.java, api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java, http/vertx/README.md, http/vertx/pom.xml, http/vertx/src/main/java/io/cloudevents/http/vertx/CeVertx.java, http/vertx/src/test/java/io/cloudevents/http/vertx/CloudEventsVertxTest.java, pom.xml
Adding initial support for http-transport, using Eclipse Vert.x
=> WIP: vertx http transport

http/vertx/pom.xml
=> Latest of vertx

http/vertx/pom.xml, http/vertx/src/main/java/io/cloudevents/http/vertx/VertxCloudEvents.java, http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxCloudEventsImpl.java, http/vertx/src/main/java/io/cloudevents/http/vertx/package-info.java, http/vertx/src/test/java/io/cloudevents/http/vertx/VertxCloudEventsTests.java
Also: rewrote the tests in RxJava2
=> Switch http-vertx tests to JUnit 5

README.md, cdi/README.md, http/vertx/README.md, http/vertx/src/test/java/io/cloudevents/http/vertx/VertxCloudEventsTests.java
=> Tweaking docs

api/src/main/java/io/cloudevents/CloudEvent.java, api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java, api/src/test/java/io/cloudevents/CloudEventBuilderTest.java, api/src/test/java/io/cloudevents/CloudEventJacksonTest.java, http/vertx/src/main/java/io/cloudevents/http/vertx/VertxCloudEvents.java, http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxCloudEventsImpl.java, http/vertx/src/test/java/io/cloudevents/http/vertx/VertxCloudEventsTests.java
=> Adding support for structured post and bug fix :boom:

README.md, cdi/README.md, http/vertx/README.md
=> Updating to 0.2.0 libraries for usage

README.md
Signed-off-by: Bruno Borges <bruno.borges@microsoft.com>
=> Update to 0.2.1

.travis.yml, README.md, api/pom.xml, api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java, api/src/main/java/io/cloudevents/json/Json.java, api/src/main/java/io/cloudevents/v02/CloudEvent.java, api/src/main/java/io/cloudevents/v02/CloudEventBuilder.java, api/src/test/java/io/cloudevents/v02/CloudEventBuilderTest.java, api/src/test/java/io/cloudevents/v02/CloudEventJacksonTest.java, api/src/test/resources/02_absent.json, api/src/test/resources/02_aws.json, pom.xml
Employing Bean Validation 2.0 and separate the impl for spec 0.2. This will make easy the evolution and to add new specs.
=> Fixing the issue #32

README.md, api/src/main/java/io/cloudevents/extensions/DistributedTracingExtension.java, api/src/main/java/io/cloudevents/json/Json.java, api/src/main/java/io/cloudevents/v02/CloudEvent.java, api/src/main/java/io/cloudevents/v02/CloudEventBuilder.java, api/src/main/java/io/cloudevents/v02/ExtensionFormat.java, api/src/test/java/io/cloudevents/v02/CloudEventJacksonTest.java, api/src/test/resources/02_extension.json, api/src/test/resources/02_new.json
=> To marshall and unmarshall extensions

.travis.deploy.sh, .travis.yml
Script directive must be single line.
Round II
Signed-off-by: Fabio José <fabiojose@gmail.com>
=> Fixing the travis deploy job

.travis.deploy.sh
Round III of the automated deployment configuration.
Signed-off-by: Fabio José <fabiojose@gmail.com>
=> Fix the keyname alias

CHANGELOG.md, README.md, api/pom.xml, api/src/main/java/io/cloudevents/v1/CloudEventImpl.java, api/src/test/java/io/cloudevents/v1/CloudEventJacksonTest.java, cdi/README.md, cdi/pom.xml, http/vertx/README.md, http/vertx/pom.xml, kafka/README.md, kafka/pom.xml, kafka/src/main/java/io/cloudevents/kafka/CloudEventsKafkaConsumer.java, kafka/src/main/java/io/cloudevents/kafka/CloudEventsKafkaProducer.java, kafka/src/main/java/io/cloudevents/v1/kafka/HeaderMapper.java, kafka/src/test/java/io/cloudevents/v02/kafka/KafkaConsumerBinaryTest.java, kafka/src/test/java/io/cloudevents/v02/kafka/KafkaConsumerStructuredTest.java, kafka/src/test/java/io/cloudevents/v02/kafka/KafkaProducerBinaryTest.java, kafka/src/test/java/io/cloudevents/v02/kafka/KafkaProducerStructuredTest.java, kafka/src/test/java/io/cloudevents/v03/kafka/KafkaConsumerBinaryTest.java, kafka/src/test/java/io/cloudevents/v03/kafka/KafkaConsumerStructuredTest.java, kafka/src/test/java/io/cloudevents/v03/kafka/KafkaProducerBinaryTest.java, kafka/src/test/java/io/cloudevents/v03/kafka/KafkaProducerStructuredTest.java, kafka/src/test/java/io/cloudevents/v1/kafka/HeaderMapperTest.java, pom.xml
- Custom validators
- Fixes (see CHANGELOG.md)
=> Release v1.1.0

pom.xml
This was not my email. Also I am removing any email reference just like the other contributors.
=> Removing wrong email

kafka/src/main/java/io/cloudevents/v1/kafka/AttributeMapper.java, kafka/src/main/java/io/cloudevents/v1/kafka/ExtensionMapper.java, kafka/src/main/java/io/cloudevents/v1/kafka/HeaderMapper.java, kafka/src/test/java/io/cloudevents/v1/kafka/ExtensionMapperTest.java, kafka/src/test/java/io/cloudevents/v1/kafka/HeaderMapperTest.java
Fixes for issue [issue#83](https://github.com/cloudevents/sdk-java/issues/93).
Adding "ce_" prefixes for CloudEvent extensions.
=> Map extensions with prefix for Kafka CloudEvent header

README.md, README_v1.md, api/pom.xml, cdi/pom.xml, formats/json-jackson/pom.xml, kafka/pom.xml, pom.xml
Also changed the README for the V2 to specify the sdk is currently under development
=> Changed version to 2.0.0-SNAPSHOT

api/pom.xml, api/src/main/java/io/cloudevents/impl/CloudEventImpl.java, api/src/test/java/io/cloudevents/impl/CloudEventImplTest.java, formats/json-jackson/pom.xml
Fix https://github.com/cloudevents/sdk-java/issues/97
=> Test for implementation of equals

.editorconfig, .travis.yml, pom.xml
Enabled deployment on master (merging this one should deploy 2.0.0-SNAPSHOT)
=> Testing matrix with various JDKs + GraalVM

.travis.yml
Temporary enabled GraalVM on PRs too
=> GraalVM travis fix

docs/index.md
Index page for the docs website. This is just a drafted page to test the website deploy.
=> Bootstrap docs

docs/index.md
=> Fixed table

api/pom.xml, api/src/main/java/io/cloudevents/Attributes.java, api/src/main/java/io/cloudevents/CloudEvent.java, api/src/main/java/io/cloudevents/impl/BaseCloudEventBuilder.java, api/src/main/java/io/cloudevents/impl/CloudEventImpl.java, api/src/main/java/io/cloudevents/lang/Nullable.java, api/src/main/java/io/cloudevents/v03/AttributesImpl.java, api/src/main/java/io/cloudevents/v03/CloudEventBuilder.java, api/src/main/java/io/cloudevents/v1/AttributesImpl.java, api/src/main/java/io/cloudevents/v1/CloudEventBuilder.java, api/src/test/java/io/cloudevents/mock/CSVFormat.java, formats/json-jackson/src/main/java/io/cloudevents/format/json/CloudEventSerializer.java
Closes #123.
Signed-off-by: Sergei Egorov <segorov@pivotal.io>
=> Introduce JSR-305 compatible nullability, remove `Optional`

.mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
This will ensure that developers have a chance to  use the same version of maven.
=> Add Maven wrapper

api/src/main/java/io/cloudevents/message/impl/MessageUtils.java, http/restful-ws/README.md, http/restful-ws/pom.xml, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/BinaryEncoding.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/CloudEventsProvider.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/StructuredEncoding.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/BinaryRestfulWSMessageImpl.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/CloudEventsHeaders.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSClientMessageVisitor.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageFactory.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageVisitor.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/Utils.java, http/restful-ws/src/main/resources/META-INF/services/javax.ws.rs.ext.MessageBodyReader, http/restful-ws/src/main/resources/META-INF/services/javax.ws.rs.ext.MessageBodyWriter, http/restful-ws/src/test/java/io/cloudevents/http/restful/ws/TestEventServer.java, http/restful-ws/src/test/java/io/cloudevents/http/restful/ws/TestResource.java, http/restful-ws/src/test/java/io/cloudevents/http/restful/ws/TestServer.java, http/restful-ws/src/test/java/io/cloudevents/http/restful/ws/jersey/TestServerJersey.java, kafka/src/main/java/io/cloudevents/kafka/impl/KafkaHeaders.java, pom.xml
=> Integration with Jakarta RESTful Web Services

.travis.yml
=> Removed quiet flag in travis build

.travis.deploy.sh, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, pom.xml
=> Fixed the maven deployment config to avoid integration test packages deploy

maintainer_guidelines.md, pr_guidelines.md
Copy some useful guidance docs from the Javascript repo
Signed-off-by: Doug Davis <dug@us.ibm.com>
=> copy guidance from javascript repo

core/src/main/java/io/cloudevents/core/extensions/DatarefExtension.java, core/src/main/java/io/cloudevents/core/provider/ExtensionProvider.java, core/src/test/java/io/cloudevents/core/extensions/DatarefExtensionTest.java
Implements dataref extension (see #70) targeting SDK version 2 (see #71)
=> Implement dataref extension

core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java, core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java, core/src/test/java/io/cloudevents/core/v1/CloudEventBuilderTest.java
This allows to use a builder as a template to create more builders #163
=> Created method to create a builder from a builder

core/src/test/java/io/cloudevents/core/message/EventMessageRoundtripTest.java, core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java, core/src/test/java/io/cloudevents/core/mock/MockStructuredMessageReader.java
=> Simplified Message mocks usage

api/pom.xml, core/pom.xml, formats/json-jackson/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml
=> Added Automatic-Module-Name to manifests of published modules

core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/extensions/DistributedTracingExtension.java, core/src/main/java/io/cloudevents/core/format/EventDeserializationException.java, core/src/main/java/io/cloudevents/core/format/EventFormat.java, core/src/main/java/io/cloudevents/core/format/EventSerializationException.java, core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java, core/src/main/java/io/cloudevents/core/message/MessageReader.java, core/src/main/java/io/cloudevents/core/message/MessageWriter.java, core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java, core/src/main/java/io/cloudevents/core/message/StructuredMessageWriter.java, core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java, core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java, core/src/main/java/io/cloudevents/core/provider/ExtensionProvider.java, core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java, core/src/test/java/io/cloudevents/core/mock/CSVFormat.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
=> Javadoc-ed cloudevents-core

http/vertx/pom.xml, http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java, kafka/pom.xml, kafka/src/main/java/io/cloudevents/kafka/KafkaMessageFactory.java
=> Javadoc-ed kafka and vertx integrations

http/restful-ws/README.md, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/BinaryEncoding.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/CloudEventsProvider.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/StructuredEncoding.java
=> Added javadoc for restful ws module

core/src/main/java/io/cloudevents/core/format/EventFormat.java, core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java, core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java, core/src/main/java/io/cloudevents/core/provider/ExtensionProvider.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java, http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java, kafka/src/main/java/io/cloudevents/kafka/KafkaMessageFactory.java
Also Javadoc-ed `cloudevents-json-jackson`
Fixes #124 
=> Now all javadocs pass the minimum checks

README.md, api/README.md, api/pom.xml, core/pom.xml, docs/index.md, formats/json-jackson/README.md, formats/json-jackson/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/README.md, http/restful-ws/pom.xml, http/vertx/README.md, http/vertx/pom.xml, kafka/README.md, kafka/pom.xml, pom.xml
=> Release 2.0.0-milestone1

pom.xml
=> Release 2.0.0-milestone1 - attempt 2

api/pom.xml, core/pom.xml, formats/json-jackson/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml
Back to SNAPSHOT after release
=> Back to SNAPSHOT

examples/kafka/README.md, examples/kafka/pom.xml, examples/kafka/src/main/java/io/cloudevents/examples/kafka/SampleConsumer.java, examples/kafka/src/main/java/io/cloudevents/examples/kafka/SampleProducer.java, examples/pom.xml, pom.xml
=> Created kafka example

api/pom.xml, formats/json-jackson/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/vertx/pom.xml, pom.xml
=> Dependency bumps

api/src/main/java/io/cloudevents/types/Time.java, api/src/test/java/io/cloudevents/types/TimeTest.java
=> Fix ZoneId in Time serialization

api/pom.xml, core/pom.xml, formats/json-jackson/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml
* Updated to latest version of junit5 and downgraded maven surefire plugin (for some reason, the latest milestones of 3.0 don't handle the latest version of junit5)
* Little reorg of the poms, to avoid repetitions
=> Bump junit5

core/pom.xml
In a previous PR this was wrongly removed
=> Added core package test-jar again to poms

api/pom.xml, benchmarks/pom.xml, core/pom.xml, examples/kafka/pom.xml, examples/pom.xml, examples/vertx/pom.xml, formats/json-jackson/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml
=> Release 2.0.0-SNAPSHOT

formats/json-jackson/README.md, http/restful-ws/README.md, http/vertx/README.md
This is part of the problem with the actual release automation described in #223
=> Fixed some docs

.travis.yml
Signed-off-by: ruromero <rromerom@redhat.com>
=> Use Graalvm 20.1.0 in CI

api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java, api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java, core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java, core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java, core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java, core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java, core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java, core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java, core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java, core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java, core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java, http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSClientMessageWriter.java, http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageWriter.java, http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxHttpServerResponseMessageWriterImpl.java, http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxWebClientRequestMessageWriterImpl.java, kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageWriterImpl.java, kafka/src/main/java/io/cloudevents/kafka/impl/KafkaProducerMessageWriterImpl.java, kafka/src/main/java/io/cloudevents/kafka/impl/KafkaSerializerMessageWriterImpl.java
=> Renamed methods of *Writers to coerce with the builder apis

.github/workflows/master.yaml, pom.xml
Trying to fix the master deploy failure (some gpg issue with maven-gpg-plugin)
=> GH Actions, round 2

.github/workflows/bump.yaml
=> Issue in the bump github action

core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java, core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java
=> Fix getAttribute("datacontentencoding") in CloudEventV03

README.md, pom.xml
=> Removed some travis leftovers

api/pom.xml, core/pom.xml, formats/json-jackson/pom.xml, http/basic/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, pom.xml
Fix some poms warnings about bad `relativePath` and `version` in child poms
=> Pom cleanup

core/src/main/java/io/cloudevents/core/message/impl/GenericStructuredMessageReader.java, http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java, http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
Last minute fix before the RC1
=> Fix NPE on null body with structured message

examples/README.md, examples/pom.xml, examples/spring-reactive/README.md, examples/spring-reactive/pom.xml, examples/spring-reactive/src/main/java/io/cloudevents/examples/spring/DemoApplication.java, examples/spring-reactive/src/main/java/io/cloudevents/examples/spring/Foo.java, examples/spring-reactive/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java
=> Add a Spring sample with webflux

docs/index.md
=> Fixed broken links on website

docs/amqp-proton.md
AMQP docs now reflects the changes introduced in 87c6915d9a4
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
=> update AMQP docs

core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java, core/src/test/java/io/cloudevents/core/provider/EventFormatProviderTest.java
This will allow a neater and more efficient implementation
of encoders and decoders.
=> Allow user to enumerate supported content types

docs/spring.md, examples/pom.xml, examples/spring-function/README.md, examples/spring-function/pom.xml, examples/spring-function/src/main/java/io/cloudevents/examples/spring/DemoApplication.java, examples/spring-function/src/main/java/io/cloudevents/examples/spring/Foo.java, examples/spring-function/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java, examples/spring-reactive/README.md
Adds a sample using Spring Cloud Function showing how to use the message converter.
=> Add Spring Cloud Function sample

api/src/main/java/io/cloudevents/CloudEventExtension.java, api/src/main/java/io/cloudevents/rw/CloudEventContextWriter.java, core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java, core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java, core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java, core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java, core/src/test/java/io/cloudevents/core/test/Data.java, formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java, formats/json-jackson/src/test/resources/v1/binary_attr.json
Added test data example
Added unit-test for JSON Format
Closes Issue #351 
Signed-off-by: Day, Jeremy(jday) <jday@paypal.com>
=> Introduced support for Binary attribute types.

benchmarks/pom.xml, benchmarks/src/main/java/io/cloudevents/bench/sql/CompileBenchmark.java, benchmarks/src/main/java/io/cloudevents/bench/sql/RunBenchmark.java
Add some test cases for CESQL implementation benchmark. Will extend this test suite in next PRs.
=> CESQL Benchmark

.github/workflows/branch.yaml, .github/workflows/pr.yaml
=> [2.1] Build release branch 

.github/workflows/branch.yaml, .github/workflows/pr.yaml
Now GH actions build release branches too
=> Build release branches

sql/src/main/java/io/cloudevents/sql/impl/expressions/LikeExpression.java, sql/src/test/resources/tck/like_expression.yaml
=> [2.1] Fix like expression

.github/workflows/pr.yaml
Additionally, run tests using Java 17.
=> Run tests with Java 17

amqp/pom.xml, api/pom.xml, benchmarks/pom.xml, core/pom.xml, examples/amqp-proton/pom.xml, examples/basic-http/pom.xml, examples/kafka/pom.xml, examples/pom.xml, examples/restful-ws-quarkus/pom.xml, examples/restful-ws-spring-boot/pom.xml, examples/spring-function/pom.xml, examples/spring-reactive/pom.xml, examples/spring-rsocket/pom.xml, examples/vertx/pom.xml, formats/json-jackson/pom.xml, formats/protobuf/pom.xml, http/basic/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml, spring/pom.xml, sql/pom.xml
Run:
```shell
export NEW_VERSION=2.2.1-SNAPSHOT
./mvnw versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false -B
```
=> [2.2] Bump version to 2.2.1-SNAPSHOT

.github/workflows/pr.yaml
=> [2.2] Run tests with Java 17 (#426)

amqp/pom.xml, api/pom.xml, benchmarks/pom.xml, core/pom.xml, examples/amqp-proton/pom.xml, examples/basic-http/pom.xml, examples/kafka/pom.xml, examples/pom.xml, examples/restful-ws-quarkus/pom.xml, examples/restful-ws-spring-boot/pom.xml, examples/spring-function/pom.xml, examples/spring-reactive/pom.xml, examples/spring-rsocket/pom.xml, examples/vertx/pom.xml, formats/json-jackson/pom.xml, formats/protobuf/pom.xml, http/basic/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml, spring/pom.xml, sql/pom.xml
Run:
```
./mvnw versions:set -DnewVersion=2.2.2-SNAPSHOT -DgenerateBackupPoms=false -B
```
=> [2.2] Bump version to 2.2.2-SNAPSHOT

amqp/pom.xml, api/pom.xml, benchmarks/pom.xml, bom/pom.xml, core/pom.xml, examples/amqp-proton/pom.xml, examples/basic-http/pom.xml, examples/kafka/pom.xml, examples/pom.xml, examples/restful-ws-quarkus/pom.xml, examples/restful-ws-spring-boot/pom.xml, examples/spring-function/pom.xml, examples/spring-reactive/pom.xml, examples/spring-rsocket/pom.xml, examples/vertx/pom.xml, formats/json-jackson/pom.xml, formats/protobuf/pom.xml, http/basic/pom.xml, http/restful-ws-integration-tests/pom.xml, http/restful-ws-integration-tests/restful-ws-common/pom.xml, http/restful-ws-integration-tests/restful-ws-jersey/pom.xml, http/restful-ws-integration-tests/restful-ws-resteasy/pom.xml, http/restful-ws-integration-tests/restful-ws-spring/pom.xml, http/restful-ws/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml, spring/pom.xml, sql/pom.xml
Run:
```
./mvnw versions:set -DnewVersion=2.3.1-SNAPSHOT -DgenerateBackupPoms=false -B
```
=> [2.3] Bump version to 2.3.1-SNAPSHOT

formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java, formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
Signed-off-by: Frederic Delechamp <fdelechamp@guidewire.com>
=> Strip parameters from data content types to assess if it's JSON format (#484)

formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java, formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonCloudEventDataTest.java, formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java, formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
=> Remove deprecated constructor usage for JsonCloudEventData

formats/protobuf/pom.xml, http/vertx/pom.xml, kafka/pom.xml, pom.xml
Closes #489
Signed-off-by: Doug Davis <dug@microsoft.com>
=> Upgrade some packages

.github/workflows/branch.yaml
=> Run tests before deploy on Java 17

.github/workflows/branch.yaml
=> [2.4] Run tests before deploy on Java 17

.github/workflows/branch.yaml, .github/workflows/pr.yaml, CONTRIBUTING.md, MAINTAINERS.md, README.md, core/src/main/java/io/cloudevents/core/extensions/DistributedTracingExtension.java, docs/_config.yml, docs/amqp-proton.md, docs/http-basic.md, docs/http-jakarta-restful-ws-jakarta.md, docs/http-jakarta-restful-ws.md, docs/http-vertx.md, docs/index.md, docs/kafka.md, docs/spring.md, examples/kafka/src/main/java/io/cloudevents/examples/kafka/SampleProducer.java, examples/vertx/src/main/java/io/cloudevents/examples/vertx/SampleHTTPClient.java, formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java, http/restful-ws-jakarta/README.md, kafka/src/main/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptor.java
Fixes https://github.com/cloudevents/sdk-java/issues/459
=> Switch default branch to main

.github/workflows/branch.yaml, .github/workflows/bump.yaml, .github/workflows/pr.yaml, pom.xml
Cherry-pick of https://github.com/cloudevents/sdk-java/pull/529 for main
=> Fix javadoc build (#529)

.github/workflows/branch.yaml, .github/workflows/pr.yaml
Support for testing version 3 and beyond
=> Run workflows on any major version branch

core/src/main/java/io/cloudevents/core/provider/CloudEventValidatorProvider.java
Cherry-pick of https://github.com/cloudevents/sdk-java/pull/650 for 4.0.1
=> [4.0] Make CloudEventValidatorProvider thread safe (#650)

.github/workflows/pr.yaml
remove maven cache because it is failing the pr build
=> build: remove maven cache

.github/workflows/branch.yaml, pom.xml
Ref: https://central.sonatype.org/publish/publish-portal-maven/
=> Migrate from OSSRH to Central Portal
